### ISSUE TITLE
KeyError 'error' in docstring when using Resnets

### ISSUE THREAD

**Issue by mjohenneken** [RichardXiao13/TensorFlow-ResNets#3]
Hi, first of all, thanks for putting out these models! They are really helpful and save me some time. 
However to be able to use the library with Tensorflow 2.4.1 a small fix has to be made. The `PREPROCESS_INPUT_DOC` includes an additional field `error` which is not provided as parameter to `.format(..`  causing this error:
```
    from tf2_resnets import models as resnet_models
  File "/home/anargh/anaconda3/envs/max-thesis/lib/python3.7/site-packages/tf2_resnets/models.py", line 1, in <module>
    from tf2_resnets.resnet import ResNet
  File "/home/anargh/anaconda3/envs/max-thesis/lib/python3.7/site-packages/tf2_resnets/resnet.py", line 298, in <module>
    ret=imagenet_utils.PREPROCESS_INPUT_RET_DOC_TORCH)
KeyError: 'error'
```
Code location:
https://github.com/RichardXiao13/TensorFlow-ResNets/blob/a77281032e2942ad30319200e2819962a4a5e600/tf2_resnets/resnet.py#L296

I think it is not a good idea to reuse docstrings as they can not be considered a stable API. So I would favor the removal of those lines

**Comment by RichardXiao13** [comment]
Sure, I will get on that.

**Comment by lthilnklover** [comment]
So to use it with tensorflow 2.4.1 is there any workaround at this moment?

**Comment by mjohenneken** [comment]
You can delete the docstring as a workaround.
https://github.com/mjohenneken/TensorFlow-ResNets/commit/a1879d8626ae03ca1b0a5d41654fddd2eb3cffb2

**Comment by atamazian** [comment]
This issue is solved, please close it.
